# Generated by Django 6.1.1 on 2026-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_keyword', models.CharField(help_text="Word to trigger this answer (e.g., 'Jharia')", max_length=100)),
                ('answer', models.TextField()),
                ('token_id', models.CharField(max_length=50)),
                ('page_number', models.IntegerField(default=1)),
            ],
        ),
    ]
